services:
  web:
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./client
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .git/
            - .next/
        - path: ./client/package.json
          action: rebuild
        - path: ./client/pnpm-lock.yaml
          action: rebuild
        - path: ./client/Dockerfile
          action: rebuild

  db:
    image: postgres:16
    container_name: tekkadb
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    depends_on:
      - db
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    volumes:
      - ./server/src/logs:/app/src/logs
    develop:
      watch:
        - path: ./server/src
          target: /app/src
          action: sync
          ignore:
            - node_modules/
            - .git/
            - logs/
        - path: ./server/package.json
          action: rebuild
        - path: ./server/pnpm-lock.yaml
          action: rebuild
        - path: ./server/Dockerfile
          action: rebuild

volumes:
  db_data: